{
  "openapi": "3.0.1",
  "info": {
    "title": "Risk Scoring API Specification",
    "description": "CyberCube's CyberConnect APIs deliver data and analytics solutions via its Model Integration APIs for the cyber insurance ecosystem. Our Risk Scoring APIs provide key support to the single-risk selection process:\n  \n  - Find account(s) for underwriting consideration using CyberCube's proprietary firmographic database.\n  \n  - Generate security and exposure risk scores to offer a composite view of an organization’s cyber risk.\n  \n  - Evaluate the risk profiles of prospective accounts, leveraging enterprise security telemetry and firmographic information to support single risk-selection and peer benchmarking.\n  \n# First Steps\nBefore using the Risk Scoring APIs, read these short guides to understand the optimal workflows and other key details:\n\n- [Get Started with Risk Scoring APIs](/risk-scoring-apis/workflow)\n- [Generate and Get Risk Scores](/risk-scoring-apis/generate-and-get-risk-scores)\n- [Export a Report](/risk-scoring-apis/exporting-a-report)\n- [Supported SIC-4 Codes](/risk-scoring-apis/supported-sic-4-codes)\n- [Signal API ID Mapping](/risk-scoring-apis/api-am-signal-api-mapping)\n\n\n# Using This Swagger API Document\n\nUse this Swagger API document to test your calls and generate Curl commands, request URLs, and server responses:\n1. Click the green **Authorize** button, enter your API key, and click **Authorize**.\n2. Expand any of the endpoint sections and click **Try it Out**.\n3. If necessary, enter any IDs or other parameter values to make the call.\n4. Click **Execute**.\n5. View your results.\n\n# Authentication\nYou must successfully authenticate to access and use our APIs. To authenticate, use the authentication key sent to you from our team. \n\nSee [Access Your API Keys](/api-authentication-and-security/read-only-api-users?root=169) for more information.\n\n# Legal Disclaimer \n\n  This document is CyberCube Analytics Inc.'s proprietary and confidential information and may not be disclosed to third parties without CyberCube’s prior written consent. This document is provided to you strictly and solely for your internal business purposes only and does not constitute actuarial, tax, legal or other professional advice. Whilst all reasonable care has been taken in the preparation of this document including in ensuring the accuracy of its content, this document is provided on an \"as is\" basis with no warranties or representations whatsoever. No liability is accepted by CyberCube and its affiliates for any loss or damage suffered as a result of reliance on any statement or opinion, or for any error or omission, or deficiency contained in this document. You shall be solely responsible and liable for all decisions you make pertaining to the use of the information contained in this document. This document also contains information that is based on third party sources which we believe to be reliable but we make no representation or warranty as to its correctness or accuracy. This document is subject to change from time to time and it is your responsibility for ensuring that you use the most updated version. Nothing herein shall be construed as conferring on you by implication or otherwise any other licence or right to use CyberCube’s intellectual property. All CyberCube's rights are reserved.\n\n# Contact Us",
    "contact": {
      "name": "CyberCube IT",
      "url": "https://www.cybcube.com",
      "email": "support@cybcube.com"
    },
    "version": "v1.0.3"
  },
  "servers": [
    {
      "url": "https://api.pm.cybcube.com",
      "description": "The CyberCube Analytics, Inc. API server."
    }
  ],
  "security": [
    {
      "Api-Key": []
    }
  ],
  "tags": [
    {
      "name": "Search Company",
      "description": "Find companies in CyberCube's firmographic database."
    },
    {
      "name": "Account Information",
      "description": "Create and manage accounts."
    },
    {
      "name": "Risk Scoring Analysis",
      "description": "Analyze accounts and manage analyses."
    },
    {
      "name": "Risk Scoring Reports",
      "description": "Retrieve analysis reports."
    },
    {
      "name": "Risk Scoring Security Signals",
      "description": "Retrieve security signal data and historical trends."
    }
  ],
  "paths": {
    "/odap/data/companies/v1/search": {
      "get": {
        "tags": [
          "Search Company"
        ],
        "summary": "Find Company",
        "description": "Search for available companies in our firmographic database. You can search by company name or website:\n\n  - Searches for names and websites are not case-sensitive.\n  - Website prefix (https:// or http://) is not required.\n  - Searches return up to 50 matching company records.",
        "operationId": "searchCompany",
        "parameters": [
          {
            "name": "query",
            "description": "Company name or website",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "minLength": 3,
              "maxLength": 200
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SearchCompanyDto"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/odap/risk-scoring/v3/accounts": {
      "post": {
        "tags": [
          "Account Information"
        ],
        "summary": "Create Account",
        "description": "Create a new account. Use the returned `accountId` in other endpoints to identify the account.",
        "operationId": "createCompany_v3",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateAccountV3Dto"
              }
            }
          },
          "required": true,
          "description": "| Property | Description | Default / Other Accepted Values | Required\n | --- | --- | --- | --- |\n | `countryCode` | Country code for the company location | No default / String| Yes\n | `policyPremium` | Premium for the account (USD) | No default / Integer > 0 | No\n | `sic4` | Standard Industrial Classification code | No default / See [Supported SIC-4 Codes](/risk-scoring-apis/supported-sic-4-codes). | Yes\n | `eil` | Unique code that identifies the company in our Enterprise Intelligence Layer | No default / String| No\n | `companyName` | Company name | No default / String| Yes\n | `attachmentPoint` | Attachment point for the account (USD) | No default / Integer > 0 | No\n | `recordsCount` | Number of records associated with the account | No default / Integer > 0 | No\n | `deductible` | Deductible for the account (USD) | No default / Integer > 0 | No\n | `limits` | Policy limit for the account (USD) | No default / Integer > 0 | No\n | `website` | Company website | No default / String | No\n | `participationPercentage` | Participation percentage for the account, expressed as a decimal, such as `0.75`. | No default / Float | No\n | `revenue` | Company revenue (USD) | No default / Integer > 0 | Yes\n | `companySize` | Company size | `LARGE` / `MEDIUM`, `SMALL`, `MICRO` | Yes\n \n \n**Note:** Optional parameters require empty strings or `null` values. You cannot manually enter 0 for a numerical value, but if you leave it blank, it will count as 0.\n \n # Coverage Properties\n \n Include or exclude coverages, set sublimit amounts, and set deductible amounts. Configure each nested property with the following values:\n \n  - `include`: `true` / `false`\n  - `sublimitAmount`: Number\n  - `deductibleAmount`: Number\n  - `deductibleType`: `Time` / `Franchise Time`\n  \n  See the table below to set the loss basis type and deductible types for `businessInterruption`, `contingentBusinessInterruption`, and `businessInterruptionLossBasis`.\n \n \n | Property | Description | Default / Other Accepted Values | Required\n | --- | --- | --- | --- |\n | `legalLiability` | Legal liability coverage | Included | No\n | `regulatoryFinesAndPenalties` | Regulatory fines and penalties coverage | Included | No\n | `investigationAndResponse` | Investigation and response coverage | Included | No\n | `dataRestoration` | Data Restoration coverage | Included | No\n | `businessInterruption` | Business interruption coverage | Included; `deductibleType`: `Time` / `Franchise Time` | No\n | `businessInterruptionLossBasis` | Loss basis calculation type for business interruption coverage | `lossBasisType`: `Revenue` / `Profit` | No\n | `contingentBusinessInterruption` | Contingent business interruption coverage | Included; `deductibleType`: `Time` / `Franchise Time` | No\n | `misdirectedPayment` | Misdirected payment coverage | Included | No\n | `extortionPayment` | Extortion payment coverage | Included | No\n \n \n**Note:** Optional parameters require empty strings or `null` values."
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccountIdDto"
                }
              }
            }
          }
        }
      }
    },
    "/odap/risk-scoring/v3/accounts/{accountId}": {
      "get": {
        "tags": [
          "Account Information"
        ],
        "summary": "View Account",
        "description": "View information for an account by using `accountID`. ",
        "operationId": "getCompany_v3",
        "parameters": [
          {
            "name": "accountId",
            "description": "ID of the account to view",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateAccountV3Dto"
                }
              }
            }
          }
        }
      }
    },
    "/odap/risk-scoring/v3/accounts/{accountId}/analyses": {
      "post": {
        "tags": [
          "Risk Scoring Analysis"
        ],
        "summary": "Run Risk Scoring Analysis",
        "description": "Run a Risk Scoring Analysis using `accountId`. Use the returned `analysisId` to get scores or download the analysis report. \n\n***Note:*** This endpoint does not download the report or show the scores. Wait at least **30 seconds** before exporting a report from the analysis.",
        "operationId": "runAnalysis_latest",
        "parameters": [
          {
            "name": "accountId",
            "in": "path",
            "description": "ID of the account to run the analysis on",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AnalysisIdDto"
                }
              }
            }
          }
        }
      }
    },
    "/odap/risk-scoring/v3/accounts/{accountId}/analyses/{analysisId}/full-report": {
      "get": {
        "tags": [
          "Risk Scoring Reports"
        ],
        "summary": "Download Risk Scoring Analysis Report",
        "description": "Get `preSignedUrl` to download a PDF report with scores and other risk analysis information by using `accountId` and `analysisId`. Keep in mind that your `preSignedUrl` is only valid for 5 minutes. \n\nDownload the report with a GET command and `preSignedUrl`. See [Export a Report](/risk-scoring-apis/exporting-a-report) for example code.\n\n***Note:*** Wait at least **30 seconds** before exporting a report from an analysis.",
        "operationId": "downloadReport_latest",
        "parameters": [
          {
            "name": "accountId",
            "in": "path",
            "description": "ID of the account",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "analysisId",
            "in": "path",
            "description": "ID of the analysis",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AmAnalysisReportDto"
                }
              }
            }
          }
        }
      }
    },
    "/odap/risk-scoring/v3/accounts/{accountId}/analyses/{analysisId}/scores": {
      "get": {
        "tags": [
          "Risk Scoring Analysis"
        ],
        "summary": "Get Risk Scores Summary",
        "description": "Get the Exposure Score, Security Score, and score-related percentile rank components of the analysis by using `accountId` and `analysisId`.",
        "operationId": "getRiskScores_v3",
        "parameters": [
          {
            "name": "accountId",
            "in": "path",
            "description": "ID of the account",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "analysisId",
            "in": "path",
            "description": "ID of the analysis to get the scores from",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LatestMonthAnalysisDataV3Dto"
                }
              }
            }
          }
        }
      }
    },
    "/odap/risk-scoring/v1/security-signals/accounts/{accountId}/analyses/{analysisId}": {
      "get": {
        "tags": [
          "Risk Scoring Security Signals"
        ],
        "summary": "Get Signal Percentile Data",
        "description": "Get signal percentile data in the primary comparative contexts offered by Account Manager. Each context is represented as one of the values for the filter parameter: `signalType`. \n\nThe other filter parameters allow you to further define the percentile output and choose which signals you generate percentile data for:\n\n  - `threatType`\n  - `signalImpact`\n  - `signalState`\n\nIf these values are left blank, all available percentile data is shown. For information on comparison types (`signalType`), see [Compare Company to Population Data](/security-signals/comparison-types?root=236). For information on signal filtering, see [Filter Security Signals](/security-signals/signal-filtering?root=236).\n\n**Notes:** \n - Percentile values are returned as integers. For example, 90% is returned as 90. \n - For each Security Signal, a maximum of 12 actionable insights are returned, based on the highest risk findings.",
        "operationId": "getSecuritySignals",
        "parameters": [
          {
            "name": "accountId",
            "in": "path",
            "description": "ID of the account",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "analysisId",
            "in": "path",
            "description": "ID of the analysis",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "threatType",
            "in": "query",
            "description": "Type of threat",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/ThreatType"
            }
          },
          {
            "name": "signalType",
            "in": "query",
            "description": "Comparison type",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/SignalType"
            }
          },
          {
            "name": "signalImpact",
            "in": "query",
            "description": "Impact type of the signal",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/SignalImpact"
            }
          },
          {
            "name": "signalState",
            "in": "query",
            "description": "State of the signal",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/SignalState"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/SecuritySignalsResponseDto"
                }
              }
            }
          }
        }
      }
    },
    "/odap/risk-scoring/v1/security-signals/historical-trends/accounts/{accountId}/analyses/{analysisId}": {
      "get": {
        "tags": [
          "Risk Scoring Security Signals"
        ],
        "summary": "Get Signal Historical Trends",
        "description": "Get signal percentile data (vs. industry, microsegment, and market) over a historical time period using `accountId` and `analysisId`. Values can go back 12 months, where each month has its own set of comparative percentile data. For more information, see [Historical Trends](/security-signals/historical-trends?root=236). \n\nYou can filter historical trend results using `signalName` to select from CyberCube's inventory of 46 signals. If left unselected, trends for all signals are shown. For a list of accepted values, see [Signal API ID Mapping](/risk-scoring-apis/api-am-signal-api-mapping) or the `SecuritySignalsDto` schema.\n\nSelect the number of months to include in the historical lookback period using `months`. Acceptable values are integers from 1 to 12.",
        "operationId": "getHistoricalSignals",
        "parameters": [
          {
            "name": "accountId",
            "in": "path",
            "description": "ID of the account",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "analysisId",
            "in": "path",
            "description": "ID of the analysis",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "signalName",
            "in": "query",
            "description": "Name of the signal",
            "required": false,
            "schema": {
              "type": "string",
              "maxLength": 100
            }
          },
          {
            "name": "months",
            "in": "query",
            "description": "Number of months in the historical period, from `1 - 12`",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32",
              "minimum": 1,
              "maximum": 12
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/SecuritySignalsHistoricalResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Scores": {
        "type": "object",
        "properties": {
          "exposure": {
            "type": "integer",
            "format": "int32",
            "minimum": 0,
            "maximum": 100
          },
          "security": {
            "type": "integer",
            "format": "int32",
            "minimum": 0,
            "maximum": 100
          }
        },
        "example": {
          "security": 85,
          "exposure": 99
        }
      },
      "SignalType": {
        "type": "string",
        "enum": [
          "COMPANY_VS_MICROSEGMENT",
          "COMPANY_VS_INDUSTRY",
          "COMPANY_VS_MARKET"
        ]
      },
      "SignalState": {
        "type": "string",
        "enum": [
          "OBSERVED",
          "NOT_OBSERVED"
        ]
      },
      "SearchCompanyDto": {
        "required": [
          "companyName",
          "eil",
          "sic4"
        ],
        "type": "object",
        "properties": {
          "eil": {
            "type": "string",
            "description": "Enterprise Identifier Link"
          },
          "companyName": {
            "type": "string",
            "minLength": 1,
            "description": "Company name"
          },
          "companySize": {
            "type": "string",
            "enum": [
              "LARGE",
              "MEDIUM",
              "MICRO",
              "SMALL"
            ],
            "minLength": 2,
            "maxLength": 2,
            "pattern": "^[A-Z]{2}$",
            "description": "ISO 3166-1 alpha-2 country code",
            "nullable": true
          },
          "sic4": {
            "type": "string",
            "minLength": 4,
            "maxLength": 4,
            "pattern": "^[0-9]{4}$",
            "description": "4-digit Standard Industrial Classification code"
          },
          "revenue": {
            "type": "number",
            "minimum": 1,
            "description": "Annual revenue in USD",
            "nullable": true
          },
          "website": {
            "type": "string",
            "maxLength": 200,
            "description": "Company website URL",
            "nullable": true
          }
        },
        "example": {
          "eil": "47e520c773889be3b7d5e72d16d8e727",
          "companyName": "Facebook Inc",
          "companySize": "LARGE",
          "countryCode": "US",
          "sic4": "7375",
          "revenue": 85965000000,
          "website": "facebook.com"
        }
      },
      "ThreatType": {
        "type": "string",
        "enum": [
          "DATA_THEFT",
          "DOUBLE_EXTORTION_RANSOMWARE",
          "RANSOMWARE",
          "PHISHING",
          "BUSINESS_EMAIL_COMPROMISE"
        ]
      },
      "PercentileRanks": {
        "type": "object",
        "properties": {
          "exposure": {
            "type": "integer",
            "format": "int32",
            "minimum": 0,
            "maximum": 100
          },
          "security": {
            "type": "integer",
            "format": "int32",
            "minimum": 0,
            "maximum": 100
          },
          "type": {
            "type": "string",
            "enum": [
              "MARKET",
              "SIZE",
              "INDUSTRY_SIZE",
              "INDUSTRY_SIZE_REGION"
            ]
          }
        },
        "example": [
          {
            "security": 85,
            "exposure": 99,
            "type": "MARKET"
          },
          {
            "security": 73,
            "exposure": 91,
            "type": "SIZE"
          },
          {
            "security": 64,
            "exposure": 52,
            "type": "INDUSTRY_SIZE"
          },
          {
            "security": 75,
            "exposure": 55,
            "type": "INDUSTRY_SIZE_REGION"
          }
        ]
      },
      "ControlCategories": {
        "type": "object",
        "properties": {
          "grc": {
            "$ref": "#/components/schemas/ControlScore"
          },
          "ncm": {
            "$ref": "#/components/schemas/ControlScore"
          },
          "iam": {
            "$ref": "#/components/schemas/ControlScore"
          },
          "vm": {
            "$ref": "#/components/schemas/ControlScore"
          },
          "md": {
            "$ref": "#/components/schemas/ControlScore"
          },
          "ir": {
            "$ref": "#/components/schemas/ControlScore"
          }
        },
        "example": {
          "grc": {
            "controlScore": 78
          },
          "ncm": {
            "controlScore": 68
          },
          "iam": {
            "controlScore": 78
          },
          "vm": {
            "controlScore": 73
          },
          "md": {
            "controlScore": 64
          },
          "ir": {
            "controlScore": 82
          }
        }
      },
      "ControlScore": {
        "type": "number"
      },
      "SignalImpact": {
        "type": "string",
        "enum": [
          "DIRECT",
          "PROXY"
        ]
      },
      "PreSignedUrl": {
        "type": "object",
        "properties": {
          "preSignedUrl": {
            "type": "string",
            "format": "url",
            "description": "Presigned URL of the report"
          },
          "httpMethod": {
            "type": "string",
            "enum": [
              "GET",
              "POST",
              "PUT",
              "DELETE",
              "HEAD",
              "PATCH"
            ],
            "description": "HTTP method allowed with presigned URL"
          }
        },
        "description": "Presigned URL of the report"
      },
      "Status": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "enum": [
              "SUCCESS",
              "ERROR",
              "RUNNING",
              "TIMEOUT"
            ],
            "description": "Status of the operation"
          },
          "code": {
            "type": "string",
            "description": "Code status of the operation",
            "nullable": true
          },
          "message": {
            "type": "string",
            "description": "message status of the operation",
            "nullable": true
          },
          "details": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "detail status of the operation",
            "nullable": true
          }
        },
        "description": "Status of the analysis",
        "example": {
          "status": "SUCCESS",
          "code": 200
        }
      },
      "AmAnalysisReportDto": {
        "type": "object",
        "properties": {
          "accountId": {
            "type": "string",
            "format": "uuid",
            "description": "Account identifier",
            "nullable": true
          },
          "analysisId": {
            "type": "string",
            "format": "uuid",
            "description": "Analysis identifier",
            "nullable": true
          },
          "reportStatus": {
            "$ref": "#/components/schemas/Status"
          },
          "report": {
            "$ref": "#/components/schemas/PreSignedUrl"
          }
        },
        "description": "Report metadata and presigned URL for downloading the report"
      },
      "CreateAccountV3Dto": {
        "required": [
          "companyName",
          "companySize",
          "countryCode",
          "revenue",
          "sic4"
        ],
        "type": "object",
        "properties": {
          "eil": {
            "type": "string",
            "maxLength": 60,
            "example": "47e520c773889be3b7d5e72d16d8e727"
          },
          "companyName": {
            "type": "string",
            "maxLength": 300,
            "example": "Facebook"
          },
          "website": {
            "type": "string",
            "example": "facebook.com"
          },
          "countryCode": {
            "type": "string",
            "maxLength": 2,
            "example": "US"
          },
          "sic4": {
            "type": "string",
            "nullable": false,
            "example": 7375
          },
          "revenue": {
            "type": "number",
            "example": 55838000000
          },
          "companySize": {
            "type": "string",
            "example": "LARGE"
          },
          "recordsCount": {
            "type": "number",
            "format": "int64",
            "example": 14560
          },
          "contractType": {
            "type": "string",
            "format": "enum - Standalone Cyber",
            "example": "Standalone Cyber"
          },
          "policyPremium": {
            "type": "number",
            "format": "int64",
            "example": 2300000
          },
          "limits": {
            "type": "number",
            "format": "int64",
            "example": 100000000
          },
          "deductible": {
            "type": "number",
            "format": "int64",
            "example": 100000
          },
          "attachmentPoint": {
            "type": "number",
            "format": "int64",
            "example": 10000
          },
          "participationPercentage": {
            "type": "number",
            "format": "double",
            "example": 0.75
          },
          "contingentBusinessInterruption": {
            "type": "object",
            "properties": {
              "include": {
                "type": "boolean",
                "example": true
              },
              "sublimitAmount": {
                "type": "number",
                "format": "int64",
                "example": 50000
              },
              "deductibleAmount": {
                "type": "number",
                "format": "int64",
                "example": 10000
              },
              "deductibleType": {
                "type": "string",
                "format": "enum - Time - Franchise_Time",
                "example": "Time"
              }
            }
          },
          "businessInterruption": {
            "type": "object",
            "properties": {
              "include": {
                "type": "boolean",
                "example": true
              },
              "sublimitAmount": {
                "type": "number",
                "format": "int64",
                "example": 40000
              },
              "deductibleAmount": {
                "type": "number",
                "format": "int64",
                "example": 10000
              },
              "deductibleType": {
                "type": "string",
                "format": "enum - Time - Franchise_Time",
                "example": "Time"
              }
            }
          },
          "misdirectedPayment": {
            "type": "object",
            "properties": {
              "include": {
                "type": "boolean"
              },
              "sublimitAmount": {
                "type": "number",
                "format": "int64",
                "example": 50000
              },
              "deductibleAmount": {
                "type": "number",
                "format": "int64",
                "example": 10000
              }
            }
          },
          "extortionPayment": {
            "type": "object",
            "properties": {
              "include": {
                "type": "boolean"
              },
              "sublimitAmount": {
                "type": "number",
                "format": "int64",
                "example": 50000
              },
              "deductibleAmount": {
                "type": "number",
                "format": "int64",
                "example": 10000
              }
            }
          },
          "regulatoryFinesAndPenalties": {
            "type": "object",
            "properties": {
              "include": {
                "type": "boolean",
                "example": true
              },
              "sublimitAmount": {
                "type": "number",
                "format": "int64",
                "example": 25000
              },
              "deductibleAmount": {
                "type": "number",
                "format": "int64",
                "example": 10000
              }
            }
          },
          "legalLiability": {
            "type": "object",
            "properties": {
              "include": {
                "type": "boolean",
                "example": true
              },
              "sublimitAmount": {
                "type": "number",
                "format": "int64",
                "example": 40000
              },
              "deductibleAmount": {
                "type": "number",
                "format": "int64",
                "example": 10000
              }
            }
          },
          "dataRestoration": {
            "type": "object",
            "properties": {
              "include": {
                "type": "boolean",
                "example": true
              },
              "sublimitAmount": {
                "type": "number",
                "format": "int64",
                "example": 20000
              },
              "deductibleAmount": {
                "type": "number",
                "format": "int64",
                "example": 10000
              }
            }
          },
          "businessInterruptionLossBasis": {
            "type": "object",
            "properties": {
              "include": {
                "type": "boolean",
                "example": true
              },
              "lossBasisType": {
                "type": "string",
                "format": "enum - Revenue - Profit",
                "example": "Revenue"
              },
              "lossBasisAmount": {
                "type": "number",
                "format": "int64",
                "example": 10000
              }
            }
          },
          "investigationAndResponse": {
            "type": "object",
            "properties": {
              "include": {
                "type": "boolean",
                "example": true
              },
              "sublimitAmount": {
                "type": "number",
                "format": "int64",
                "example": 60000
              },
              "deductibleAmount": {
                "type": "number",
                "format": "int64",
                "example": 10000
              }
            }
          }
        }
      },
      "AccountIdDto": {
        "type": "object",
        "properties": {
          "accountId": {
            "type": "string",
            "format": "uuid",
            "description": "Unique account identifier"
          }
        }
      },
      "AnalysisIdDto": {
        "type": "object",
        "properties": {
          "analysisId": {
            "type": "string",
            "format": "uuid",
            "description": "Unique analysis identifier"
          }
        }
      },
      "LatestMonthAnalysisDataV3Dto": {
        "type": "object",
        "properties": {
          "accountId": {
            "type": "string",
            "format": "uuid",
            "description": "Account identifier",
            "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          },
          "analysisId": {
            "type": "string",
            "format": "uuid",
            "description": "Analysis identifier",
            "example": "ff15829d-8b97-4d78-b6c7-0d02bec9318a"
          },
          "analysisStatus": {
            "$ref": "#/components/schemas/Status"
          },
          "executionDate": {
            "type": "string",
            "example": "2025-11-11"
          },
          "scores": {
            "$ref": "#/components/schemas/Scores"
          },
          "scoreBasis": {
            "type": "string",
            "enum": [
              "COMPANY_SPECIFIC_SIGNALS",
              "MICROSEGMENT_FALLBACKS"
            ]
          },
          "percentileRanks": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PercentileRanks"
            },
            "nullable": true
          },
          "controlCategories": {
            "$ref": "#/components/schemas/ControlCategories"
          }
        }
      },
      "SecuritySignalsResponseDto": {
        "type": "object",
        "properties": {
          "accountId": {
            "type": "string",
            "format": "uuid"
          },
          "analysisId": {
            "type": "string",
            "format": "uuid"
          },
          "analysisStatus": {
            "$ref": "#/components/schemas/Status"
          },
          "executionDate": {
            "type": "string",
            "example": "2025-11-11"
          },
          "securitySignals": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/SecuritySignalsDto"
            }
          }
        },
        "example": {
          "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "analysisId": "d086ed4b-3408-4807-a23f-7cfb6d4a20f4",
          "analysisStatus": {
            "status": "SUCCESS",
            "code": "200 OK"
          },
          "executionDate": "2026-02-18",
          "securitySignals": [
            {
              "signalName": "REDUNDANT HOSTING",
              "signalState": "OBSERVED",
              "signalDetails": [
                {
                  "signalType": "COMPANY_VS_INDUSTRY",
                  "percentile": 99
                },
                {
                  "signalType": "COMPANY_VS_MICROSEGMENT",
                  "percentile": 95
                },
                {
                  "signalType": "COMPANY_VS_ALL_COMPANIES",
                  "percentile": 90
                }
              ],
              "actionableFindings": [
                {
                  "vendor": "Verizon",
                  "technologyCategory": "DNS",
                  "product": "Verizon DNS"
                }
              ],
              "countRange": "50-75"
            }
          ]
        }
      },
      "SecuritySignalsHistoricalResponse": {
        "type": "object",
        "properties": {
          "accountId": {
            "type": "string",
            "format": "uuid"
          },
          "analysisId": {
            "type": "string",
            "format": "uuid"
          },
          "analysisStatus": {
            "$ref": "#/components/schemas/Status"
          },
          "executionDate": {
            "type": "string",
            "example": "2025-11-11"
          },
          "securitySignals": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/SecuritySignalsDto"
            }
          }
        },
        "example": {
          "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "analysisId": "d086ed4b-3408-4807-a23f-7cfb6d4a20f4",
          "analysisStatus": {
            "status": "SUCCESS",
            "code": "200 OK"
          },
          "executionDate": "2026-01-11",
          "securitySignals": [
            {
              "signalName": "REDUNDANT HOSTING",
              "month": "1",
              "signalDetails": [
                {
                  "signalType": "COMPANY_VS_INDUSTRY",
                  "percentile": 98
                },
                {
                  "signalType": "COMPANY_VS_MICROSEGMENT",
                  "percentile": 95
                },
                {
                  "signalType": "COMPANY_VS_ALL_COMPANIES",
                  "percentile": 90
                }
              ]
            },
            {
              "signalName": "REDUNDANT HOSTING",
              "month": "2",
              "signalDetails": [
                {
                  "signalType": "COMPANY_VS_INDUSTRY",
                  "percentile": 99
                },
                {
                  "signalType": "COMPANY_VS_MICROSEGMENT",
                  "percentile": 95
                },
                {
                  "signalType": "COMPANY_VS_ALL_COMPANIES",
                  "percentile": 91
                }
              ]
            }
          ]
        }
      },
      "SecuritySignalsDto": {
        "type": "object",
        "properties": {
          "signalName": {
            "type": "string",
            "enum": [
              "REDUNDANT_HOSTING",
              "DATA_RECOVERY",
              "MOBILE_DEVICE_MANAGEMENT",
              "EMAIL_SECURITY_TECHNOLOGIES",
              "MFA_TECHNOLOGIES",
              "SIEM_TECHNOLOGIES",
              "RW_VULNERABILITIES",
              "RW_VULNERABILITIES_LESS_30",
              "RW_VULNERABILITIES_LESS_30_120",
              "RW_VULNERABILITIES_LESS_120_MORE",
              "RW_RDP_OPEN_PORTS",
              "RW_RDP_OPEN_PORTS_LESS_30",
              "RW_RDP_OPEN_PORTS_30_120",
              "RW_RDP_OPEN_PORTS_120_MORE",
              "RW_TOOLKIT",
              "RW_TOOLKIT_LESS_4",
              "RW_TOOLKIT_4_40",
              "RW_TOOLKIT_40_MORE",
              "RW_INFECTIONS",
              "RW_INFECTIONS_LESS_30",
              "RW_INFECTIONS_30_120",
              "RW_INFECTIONS_120_MORE",
              "EOL",
              "BANNERS",
              "VULNERABLE_HOSTS",
              "SSL",
              "SINKHOLES",
              "RISK_LEVEL",
              "PROP_OLD_SSL",
              "PROP_MOBILE",
              "BAD_PLUGINS",
              "GOOD_PLUGINS",
              "TOR",
              "WHITELIST_IP",
              "DATA_DUMPS",
              "TYPOSQUATS",
              "EMAIL_SECURITY",
              "DOMAIN_CONFIGURATION",
              "RANSOMWARE_EXTORTION",
              "WEBSITE_TECHNOLOGY",
              "INFRASTRUCTURE_INFECTIONS",
              "INFRASTRUCTURE_ABUSE",
              "NETWORK_MISCONFIGURATIONS",
              "PROP_BAD_TLDS",
              "OUTDATED_BROWSERS",
              "OUTDATED_OS",
              "RW_VULNERABILITIES_30_120",
              "RW_VULNERABILITIES_120_MORE",
              "LEAKED_PASSWDS",
              "SUSPICIOUS_TRAFFIC",
              "WEAK_ENCTYPTION",
              "TOP_ABUSED_TLD",
              "TRAFFIC_MOBILE"
            ]
          },
          "month": {
            "type": "string"
          },
          "signalState": {
            "type": "string",
            "enum": [
              "OBSERVED",
              "NOT_OBSERVED"
            ]
          },
          "signalDetails": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/SignalDetails"
            }
          },
          "actionableFindings": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ActionableFinding"
            }
          },
          "countRange": {
            "type": "string"
          }
        }
      },
      "ActionableFinding": {
        "type": "object",
        "properties": {
          "vendor": {
            "type": "string",
            "description": "Vendor of the impacted technology"
          },
          "technologyCategory": {
            "type": "string",
            "description": "Category of the impacted technology"
          },
          "product": {
            "type": "string",
            "description": "Specific name of the impacted technology"
          }
        }
      },
      "SignalDetails": {
        "type": "object",
        "properties": {
          "signalType": {
            "$ref": "#/components/schemas/SignalType"
          },
          "percentile": {
            "type": "number"
          }
        }
      }
    },
    "securitySchemes": {
      "Api-Key": {
        "type": "apiKey",
        "description": "API Key used for authentication",
        "name": "x-api-key",
        "in": "header"
      }
    }
  }
}